<Project>
  <PropertyGroup>
	<LangVersion>latest</LangVersion>

	<Nullable>enable</Nullable>
	<WarningsAsErrors>Nullable</WarningsAsErrors>

	<ImplicitUsings>enable</ImplicitUsings>

	<TargetFramework>net10.0</TargetFramework>
	<AnalysisLevel>latest-all</AnalysisLevel>
	<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

	<AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>

	<GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
	<!-- Don't block development work; but block CI if dev work isn't complete. -->
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>

	<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	<EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>
</Project>
