<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<RootNamespace>VsaTemplate.Scaffold</RootNamespace>

	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<OutputType>exe</OutputType>

	<AccelerateBuildsInVisualStudio>false</AccelerateBuildsInVisualStudio>
  </PropertyGroup>

  <ItemGroup>
	<Compile Include="../SourceGen/EquatableReadOnlyList.cs" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Humanizer" />
	<PackageReference Include="linq2db" />
	<PackageReference Include="Microsoft.Data.SqlClient" />
	<PackageReference Include="Spectre.Console.Cli" />
	<PackageReference Include="SuperLinq" />
  </ItemGroup>

</Project>
